//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamBot.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamBot.Localization.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите float скина..
        /// </summary>
        public static string EnterFloatText {
            get {
                return ResourceManager.GetString("EnterFloatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожайлуства укажите вашу ссылку на трейд. Ее можно получить [тут](https://steamcommunity.com/id/me/tradeoffers/privacy#trade_offer_access_url).
        /// </summary>
        public static string EnterTradeUrlText {
            get {
                return ResourceManager.GetString("EnterTradeUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуства укажите валидную ссылку.
        /// </summary>
        public static string EnterUrlText {
            get {
                return ResourceManager.GetString("EnterUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закаленное в боях.
        /// </summary>
        public static string Float_Battle_Scarred {
            get {
                return ResourceManager.GetString("Float_Battle_Scarred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямо из завода.
        /// </summary>
        public static string Float_Factory_New {
            get {
                return ResourceManager.GetString("Float_Factory_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После полевых испытаний.
        /// </summary>
        public static string Float_Field_Tested {
            get {
                return ResourceManager.GetString("Float_Field_Tested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немного поношенное.
        /// </summary>
        public static string Float_Minimal_Wear {
            get {
                return ResourceManager.GetString("Float_Minimal_Wear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поношенное .
        /// </summary>
        public static string Float_Well_Worn {
            get {
                return ResourceManager.GetString("Float_Well_Worn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои Средства.
        /// </summary>
        public static string MyMoneyBtn {
            get {
                return ResourceManager.GetString("MyMoneyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        public static string MyStats {
            get {
                return ResourceManager.GetString("MyStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои Сделки.
        /// </summary>
        public static string MyTradesBtn {
            get {
                return ResourceManager.GetString("MyTradesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая Сделка.
        /// </summary>
        public static string NewTradeBtn {
            get {
                return ResourceManager.GetString("NewTradeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишите название предмета:.
        /// </summary>
        public static string NewTradeText {
            get {
                return ResourceManager.GetString("NewTradeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это бот для продажи скинов CS:GO за реальные деньги..
        /// </summary>
        public static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string YesBtn {
            get {
                return ResourceManager.GetString("YesBtn", resourceCulture);
            }
        }
    }
}
